"""empty message

Revision ID: 0f3a65a88c93
Revises: b575c0acf452
Create Date: 2025-04-27 18:46:12.967852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3a65a88c93'
down_revision: Union[str, None] = 'b575c0acf452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_history_payments', sa.Column('user_service_get_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'user_history_payments', 'user_service_gets', ['user_service_get_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_history_payments', type_='foreignkey')
    op.drop_column('user_history_payments', 'user_service_get_id')
    # ### end Alembic commands ###