"""empty message

Revision ID: b575c0acf452
Revises: 
Create Date: 2025-04-27 16:32:32.827694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b575c0acf452'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('America/Bogota', now())"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_created_at'), 'categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('America/Bogota', now())"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('roles_id', sa.UUID(), nullable=True),
    sa.Column('profile_picture', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('document', sa.String(length=150), nullable=True),
    sa.Column('type_document', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('place_id', sa.String(length=150), nullable=True),
    sa.Column('whatsapp', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('America/Bogota', now())"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('clients_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('America/Bogota', now())"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_users_created_at'), 'clients_users', ['created_at'], unique=False)
    op.create_index(op.f('ix_clients_users_id'), 'clients_users', ['id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('ext', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('folder', sa.String(length=255), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('America/Bogota', now())"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_created_at'), 'files', ['created_at'], unique=False)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_table('clients_frequently_asked_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('America/Bogota', now())"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_frequently_asked_questions_created_at'), 'clients_frequently_asked_questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_clients_frequently_asked_questions_id'), 'clients_frequently_asked_questions', ['id'], unique=False)
    op.create_table('clients_reviews_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('America/Bogota', now())"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_reviews_services_created_at'), 'clients_reviews_services', ['created_at'], unique=False)
    op.create_index(op.f('ix_clients_reviews_services_id'), 'clients_reviews_services', ['id'], unique=False)
    op.create_table('clients_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('price_hour', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('delivery', sa.Boolean(), nullable=True),
    sa.Column('day_week', sa.ARRAY(sa.String(length=5)), nullable=True),
    sa.Column('range_hours', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('place_id', sa.String(length=150), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('America/Bogota', now())"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_services_created_at'), 'clients_services', ['created_at'], unique=False)
    op.create_index(op.f('ix_clients_services_id'), 'clients_services', ['id'], unique=False)
    op.create_table('history_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('bank_code', sa.String(length=150), nullable=True),
    sa.Column('reference', sa.String(length=150), nullable=True),
    sa.Column('dates', sa.String(length=150), nullable=True),
    sa.Column('concept', sa.String(length=150), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('America/Bogota', now())"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_payments_created_at'), 'history_payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_history_payments_id'), 'history_payments', ['id'], unique=False)
    op.create_table('user_history_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('history_payment_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('concept', sa.String(length=150), nullable=True),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('dates', sa.String(length=150), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('America/Bogota', now())"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients_users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['history_payment_id'], ['history_payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_history_payments_created_at'), 'user_history_payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_history_payments_id'), 'user_history_payments', ['id'], unique=False)
    op.create_table('user_service_gets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('client_services_id', sa.UUID(), nullable=True),
    sa.Column('conclude', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('date', sa.String(length=150), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('total_hour', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('America/Bogota', now())"), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients_users.id'], ),
    sa.ForeignKeyConstraint(['client_services_id'], ['clients_services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_service_gets_created_at'), 'user_service_gets', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_service_gets_id'), 'user_service_gets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_service_gets_id'), table_name='user_service_gets')
    op.drop_index(op.f('ix_user_service_gets_created_at'), table_name='user_service_gets')
    op.drop_table('user_service_gets')
    op.drop_index(op.f('ix_user_history_payments_id'), table_name='user_history_payments')
    op.drop_index(op.f('ix_user_history_payments_created_at'), table_name='user_history_payments')
    op.drop_table('user_history_payments')
    op.drop_index(op.f('ix_history_payments_id'), table_name='history_payments')
    op.drop_index(op.f('ix_history_payments_created_at'), table_name='history_payments')
    op.drop_table('history_payments')
    op.drop_index(op.f('ix_clients_services_id'), table_name='clients_services')
    op.drop_index(op.f('ix_clients_services_created_at'), table_name='clients_services')
    op.drop_table('clients_services')
    op.drop_index(op.f('ix_clients_reviews_services_id'), table_name='clients_reviews_services')
    op.drop_index(op.f('ix_clients_reviews_services_created_at'), table_name='clients_reviews_services')
    op.drop_table('clients_reviews_services')
    op.drop_index(op.f('ix_clients_frequently_asked_questions_id'), table_name='clients_frequently_asked_questions')
    op.drop_index(op.f('ix_clients_frequently_asked_questions_created_at'), table_name='clients_frequently_asked_questions')
    op.drop_table('clients_frequently_asked_questions')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_created_at'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_clients_users_id'), table_name='clients_users')
    op.drop_index(op.f('ix_clients_users_created_at'), table_name='clients_users')
    op.drop_table('clients_users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_created_at'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###